[project]
name = "wolkenschloss_tests"
version = "0.0.0"
description = ""
authors = [{ name = "Maximilian Homann", email = "geothain@pm.me" }]
license = "AGPL-3.0-or-later"
requires-python = ">=3.14"
dependencies = ["pytest (>=9.0.2,<10.0.0)", "nixos-test-driver"]

[project.optional-dependencies]
dev = ["ty"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
usertest = ["py.typed"]

[tool.pytest.ini_options]
log_cli = true

[tool.ty.src]
include = ["src"]

[tool.ty.rules]
unresolved-import = "error"
