[project]
name = "test-lib"
version = "0.0.0"
description = ""
authors = [{ name = "Maximilian Homann", email = "geothain@pm.me" }]
license = "AGPL-3.0-or-later"
requires-python = ">=3.14"
dependencies = ["pytest (>=9.0.2,<10.0.0)"]

[build-system]
requires = ["uv_build >= 0.11.19, <0.12.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
log_cli = true

[tool.uv.build-backend]
module-root = ""
